	<!-- List group -->
	<ul class="list-group">
		<?php
		$affiliate_id=$data["affiliateID"];
		if($data['artists'] && is_array($data['artists'])):
			$affiliate_url='';
		if( !empty( $affiliate_id ) ) {
			$affiliate_url = '?aid='.$affiliate_id;
			$track_url     = '&fb_track=1';
		}	
		else{
			$track_url     = '?fb_track=1';
		}
		foreach ($data['artists'] as $key => $artist) {
			?>
			<li class="list-group-item">
				<div  class="row">
					<div class="col-lg-3">
						<?php echo date( 'M d' , strtotime($artist['datetime_local'] )); ?>
					</div>
					<div class="col-lg-6">
						<?php
						$artist_name=strtolower($artist['title']);
						$title_url = 'http://seatgeek.com/'.$artist_name.'-tickets/'.$affiliate_url;					
						echo '<h4><a href="'. $title_url .'" target="_blank">'. $artist['title'] .'</a></h4>'; 
						?>
						
						<span><?php
							$address = $artist['venue']['extended_address'];
							$zip_code = substr($address, -5);
							if (is_numeric($zip_code))
								$address = substr($address, 0, strlen($address) - 5);	
							echo $artist['venue']['name'] . ', ' .  $address; ?></span>
						</div>
						<div class="col-lg-3">
							<?php 
							$url=$artist['url'].$affiliate_url;
							if( $artist['stats']['lowest_price']>0){
								$buttontitle="From $".$artist['stats']['lowest_price'];
							}else{
								$buttontitle="Find Tickets";
							}
							?>
							<a class="btn btn-success" target="_blank" href="<?php echo $url; ?>" ><?php  echo $buttontitle;?></a>
							
							
						</div>
					</div>
				</li>

				<?php }
				else: ?>
				<li class="list-group-item">
					No Record Found
				</li>
			<?php endif; ?>

		</ul>