<!-- List group -->
	<ul class="list-group">
		<?php
		
		if($data['events'] && is_array($data['events'])):
			$affiliate_url='';
			if( !empty( $affiliate_id ) ) {
				$affiliate_url = '?aid='.$affiliate_id;
				$track_url     = '&fb_track=1';
			}	
			else{
				$track_url     = '?fb_track=1';
			}
			foreach ($data['events'] as $key => $event) {
				?>
				<li class="list-group-item">
					<div  class="row">
						<div class="col-lg-3">
							<?php echo date( 'M d' , strtotime($event['datetime_local'] )); ?>
						</div>
						<div class="col-lg-6">
							<?php
							$event_name=strtolower($event['title']);
								$title_url = 'http://seatgeek.com/'.$event_name.'-tickets/'.$affiliate_url;					
							echo '<h4><a href="'. $title_url .'" target="_blank">'. $event['title'] .'</a></h4>'; 
							?>
							
							<span><?php
								$address = $event['venue']['extended_address'];
								$zip_code = substr($address, -5);
								if (is_numeric($zip_code))
									$address = substr($address, 0, strlen($address) - 5);	
								echo $event['venue']['name'] . ', ' .  $address; ?></span>
							</div>
							<div class="col-lg-3">
								<?php 
								$url=$event['url'].$affiliate_url;
								if( $event['stats']['lowest_price']>0){
									$buttontitle="From $".$event['stats']['lowest_price'];
								}else{
									$buttontitle="Find Tickets";
								}
									?>
									<a class="btn btn-success" target="_blank" href="<?php echo $url; ?>" ><?php  echo $buttontitle;?></a>
									
									
								</div>
							</div>
						</li>

						<?php }
						else: ?>
						<li class="list-group-item">
							No Record Found
						</li>
					<?php endif; ?>

				</ul>

			